### ISSUE TITLE
Timezone settings breaking plugin

### ISSUE THREAD

**Issue by nCrafts** [WP-API/WP-API#1087]
When I changed my timezone from UTC to UTC + 5:30, the plugin broke.

```
PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone (Etc/GMT+5.5)' in /var/www/wp-content/plugins/json-rest-api/plugin.php:672
Stack trace:
#0 /var/www/wp-content/plugins/json-rest-api/plugin.php(672): DateTimeZone->__construct('Etc/GMT+5.5')
#1 /var/www/wp-content/plugins/json-rest-api/lib/class-wp-json-posts.php(584): json_get_timezone()
#2 /var/www/wp-content/plugins/json-rest-api/lib/class-wp-json-posts.php(188): WP_JSON_Posts->prepare_post(Array, 'view')
#3 [internal function]: WP_JSON_Posts->get_posts(Array, 'view', 'addon', 1)
#4 /var/www/wp-content/plugins/json-rest-api/lib/class-wp-json-server.php(444): call_user_func_array(Array, Array)
#5 /var/www/wp-content/plugins/json-rest-api/lib/class-wp-json-server.php(248): WP_JSON_Server->dispatch()
#6 /var/www/wp-content/plugins/json-rest-api/plugin.php(182): WP_JSON_Server->serve_request('/posts')
#7 [internal function]: json_api_loaded('')\n#8 /var/www/wp-includes/plugin.php(496): call_user_func_array('json_ap in /var/www/wp-content/plugins/json-rest-api/plugin.php on line 672
```

Switching back to UTC fixes the issue.

**Comment by rmccue** [comment]
In v1, we made the mistake of trying to use DateTimeZone. Unfortunately, that relies on having full timezone identifiers, whereas WP can use TZ identifiers or manual offsets. In your case, you're using a manual offset which doesn't exist as a DTZ identifier, so it breaks.

Version 2 switches back to the classic style of timezones (i.e. without DateTimeZone), so should work for you here. Alternatively, if you pick `Asia/Kolkata` instead, this should also work.
